# Generated by Django 4.2.1 on 2023-05-23 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category_main_category_sub_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_category',
            old_name='ctegory',
            new_name='category',
        ),
    ]
