# Generated by Django 4.2.1 on 2023-05-24 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='app_Product',
        ),
    ]
